# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Punctuality', models.FloatField()),
                ('Food', models.FloatField()),
                ('Crowd', models.FloatField()),
                ('Services', models.FloatField()),
                ('Cooling', models.FloatField()),
                ('SeatAvailability', models.FloatField()),
            ],
        ),
    ]
