# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainstat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
    ]
