# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainstat', '0002_auto_20160402_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
            ],
        ),
    ]
